---
- name: Install Build Manager Packages
  action: apt pkg={{item}} state=installed
  with_items:
  - scons
  - cmake
  - cmake-curses-gui
  - ninja-build
  - ninja-build-doc
  - autoconf
  - automake*
  - autotools-dev
  - ant
  - ant-optional

- name: Install Shell Packages
  action: apt pkg={{item}} state=installed
  with_items:
  - bash-completion
  - csh
  - ksh

- name: Install Shell Tools Packages
  action: apt pkg={{item}} state=installed
  with_items:
  - gawk
  - graphviz
  - cpufrequtils
  - imagemagick
  - gnuplot
  - realpath
  - wget
  - curl
  - zip
  - time
  - p7zip-full

- name: Install Profile Packages
  action: apt pkg={{item}} state=installed
  with_items:
  - gperf
  - gdb
  - gdb-multiarch
  - valgrind
  - oprofile
  - elfutils
  - google-perftools
  - libgoogle-perftools-dev
  - libgoogle-perftools4

- name: Install Python2 Packages
  action: apt pkg={{item}} state=installed
  with_items:
  - python-setuptools
  - python
  - python-psutil
  - python-dev
  - libpython-dev
  - python-numpy
  - python-scipy
  - python-yaml

- name: Install Python3 Packages
  action: apt pkg={{item}} state=installed
  with_items:
  - python3
  - python3-dev
  - libpython3-dev
  - python3-numpy
  - python3-scipy
  - python3-yaml

- name: Install Boost
  action: apt pkg={{item}} state=installed
  with_items:
    - libboost-all-dev

- name: Install MPI Packages
  action: apt pkg={{item}} state=installed
  with_items:
    - mpich
    - openmpi-bin
    - libopenmpi-dev
