---

- name: Setting APT Source List
  when: ansible_distribution == 'Ubuntu'
  template: src=sources.list.j2 dest=/etc/apt/sources.list

- name: apt-get update & upgrade
  when: ansible_distribution == 'Ubuntu'
  apt: upgrade=dist update_cache=yes cache_valid_time=3600 autoremove=yes
  ignore_errors: yes 

