---

- name: Setting Network Interfaces
  when: ansible_distribution == 'Ubuntu'
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify: Restart Network

- name: Setting Internal Interface
  when: ansible_distribution == 'Ubuntu'
  template: src=internal.j2 dest=/etc/network/interfaces.d/internal.cfg
  notify: Restart Network

- name: Setting External Interface
  when: ansible_distribution == 'Ubuntu'
  template: src=external.j2 dest=/etc/network/interfaces.d/external.cfg
  notify: Restart Network

- name: Install iptables
  when: ansible_distribution == 'Ubuntu'
  action: apt pkg={{item}} state=installed
  with_items:
  - iptables-persistent

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: True

- name: Setting Iptables
  when: ansible_distribution == 'Ubuntu'
  template: src=iptables.j2 dest=/etc/iptables/rules.v4 
  notify: Restart Iptables
