---
- name: Restart bind9
  service: name={{ item }} state=restarted
  with_items:
    - bind9

- name: Reload Daemon
  command: systemctl daemon-reload

- name: Restart Cobbler Daemon
  service: name={{ item }} state=restarted
  with_items:
    - cobblerd
  notify: Reload Daemon

- name: Restart Apache2 and Cobbler Daemons
  service: name={{ item }} state=restarted
  with_items:
    - apache2
    - cobblerd
  notify: Reload Daemon
