---

- name: Install Text Editors Packages
  action: apt pkg={{item}} state=installed
  with_items:
  - emacs
  - vim
  - nano
  - cscope
  - exuberant-ctags

- name: Install Text Graphical Editors Packages
  action: apt pkg={{item}} state=installed
  with_items:
  - vim-gtk
  - vim-gtk3
  - vim-gnome
  - gedit

